// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DOTNET_PIZZA_APP.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240131201644_UpdateRelationships")]
    partial class UpdateRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrinkSizeDrinkType", b =>
                {
                    b.Property<string>("DrinkSizesId")
                        .HasColumnType("text");

                    b.Property<string>("DrinkTypesId")
                        .HasColumnType("text");

                    b.HasKey("DrinkSizesId", "DrinkTypesId");

                    b.HasIndex("DrinkTypesId");

                    b.ToTable("DrinkSizeDrinkType");
                });

            modelBuilder.Entity("PizzaModels.DrinkSize", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DrinkSizeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DrinkSizePrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("DrinkSizes");
                });

            modelBuilder.Entity("PizzaModels.DrinkType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DrinkTypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrinkTypes");
                });

            modelBuilder.Entity("PizzaModels.Order", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("OrderPrice")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PizzaModels.OrderItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("DrinkSizeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DrinkTypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("PizzaSizeId")
                        .HasColumnType("text");

                    b.Property<string>("PizzaTypeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrinkSizeId");

                    b.HasIndex("DrinkTypeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PizzaSizeId");

                    b.HasIndex("PizzaTypeId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("PizzaModels.PizzaPrice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("PizzaPriceAmount")
                        .HasColumnType("integer");

                    b.Property<string>("PizzaSizeId")
                        .HasColumnType("text");

                    b.Property<string>("PizzaTypeId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PizzaSizeId");

                    b.HasIndex("PizzaTypeId");

                    b.ToTable("PizzaPrices");
                });

            modelBuilder.Entity("PizzaModels.PizzaSize", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PizzaSizeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PizzaSizes");
                });

            modelBuilder.Entity("PizzaModels.PizzaToppings", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ToppingName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PizzaToppings");
                });

            modelBuilder.Entity("PizzaModels.PizzaType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("PizzaDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PizzaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PizzaTypes");
                });

            modelBuilder.Entity("PizzaSizePizzaType", b =>
                {
                    b.Property<string>("PizzaSizesId")
                        .HasColumnType("text");

                    b.Property<string>("PizzaTypesId")
                        .HasColumnType("text");

                    b.HasKey("PizzaSizesId", "PizzaTypesId");

                    b.HasIndex("PizzaTypesId");

                    b.ToTable("PizzaSizePizzaType");
                });

            modelBuilder.Entity("PizzaToppingsPizzaType", b =>
                {
                    b.Property<string>("PizzaToppingsId")
                        .HasColumnType("text");

                    b.Property<string>("PizzaTypesId")
                        .HasColumnType("text");

                    b.HasKey("PizzaToppingsId", "PizzaTypesId");

                    b.HasIndex("PizzaTypesId");

                    b.ToTable("PizzaToppingsPizzaType");
                });

            modelBuilder.Entity("DrinkSizeDrinkType", b =>
                {
                    b.HasOne("PizzaModels.DrinkSize", null)
                        .WithMany()
                        .HasForeignKey("DrinkSizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaModels.DrinkType", null)
                        .WithMany()
                        .HasForeignKey("DrinkTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaModels.OrderItem", b =>
                {
                    b.HasOne("PizzaModels.DrinkSize", "DrinkSize")
                        .WithMany()
                        .HasForeignKey("DrinkSizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaModels.DrinkType", "DrinkType")
                        .WithMany()
                        .HasForeignKey("DrinkTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaModels.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.HasOne("PizzaModels.PizzaSize", "PizzaSize")
                        .WithMany()
                        .HasForeignKey("PizzaSizeId");

                    b.HasOne("PizzaModels.PizzaType", "PizzaType")
                        .WithMany()
                        .HasForeignKey("PizzaTypeId");

                    b.Navigation("DrinkSize");

                    b.Navigation("DrinkType");

                    b.Navigation("PizzaSize");

                    b.Navigation("PizzaType");
                });

            modelBuilder.Entity("PizzaModels.PizzaPrice", b =>
                {
                    b.HasOne("PizzaModels.PizzaSize", "PizzaSize")
                        .WithMany()
                        .HasForeignKey("PizzaSizeId");

                    b.HasOne("PizzaModels.PizzaType", "PizzaType")
                        .WithMany()
                        .HasForeignKey("PizzaTypeId");

                    b.Navigation("PizzaSize");

                    b.Navigation("PizzaType");
                });

            modelBuilder.Entity("PizzaSizePizzaType", b =>
                {
                    b.HasOne("PizzaModels.PizzaSize", null)
                        .WithMany()
                        .HasForeignKey("PizzaSizesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaModels.PizzaType", null)
                        .WithMany()
                        .HasForeignKey("PizzaTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaToppingsPizzaType", b =>
                {
                    b.HasOne("PizzaModels.PizzaToppings", null)
                        .WithMany()
                        .HasForeignKey("PizzaToppingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PizzaModels.PizzaType", null)
                        .WithMany()
                        .HasForeignKey("PizzaTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PizzaModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
